# Site settings
title: Blog do Michael Fidelis
description: FullStack Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Michael Fidelis
user_description: Desenvolvedor fullstack, entusiasta de novas tecnologias e apaixonado pelo que faço! Sou péssimo com design (confesso), mas adoro pôr a mão na massa. Codificar, interagir, ajudar no desenho da solução e, claro, ver as coisas funcionando. Vez ou outra ajudo uma galera a aprender a programar, seja com mini cursos, projetos ou um bate papo. Trabalho com java, mas vivo por aí, entre outras liguagens :)
user_title: Desenvolvedor de Software
email: mclexr@gmail.com
twitter_username: mclexr
github_username:  michaelfidelis
gplus_username:  +MichaelFidelisDev

# Google-analytics
google-analytics:
  id: "UA-72547169-1"

exclude: ['package.json', 'src' , 'node_modules']
